import { Skills } from "lib/domains/dnd/skills";
import type { ClassDefinition } from "./types";

const allSkills = Skills.map((s) => s.label);

export const classDefinitions: Record<string, ClassDefinition> = {
  Barbarian: {
    name: "Barbarian",
    hitDice: "d12",
    baseHP: 12,
    savingThrows: ["strength", "constitution"],
    skillChoices: 2,
    availableSkills: ["Animal Handling", "Athletics", "Intimidation", "Nature", "Perception", "Survival"],
    spellcastingAbility: null,
    spellSlots: [],
    classConsumables: [{ label: "Rage", uses: 2, resetOn: "long-rest" }],
    acTemplate: "{{ add 10 (modifier abilities.dexterity) (modifier abilities.constitution) }}",
    optimizedAbilities: { strength: 15, dexterity: 13, constitution: 14, intelligence: 8, wisdom: 12, charisma: 10 },
  },
  Bard: {
    name: "Bard",
    hitDice: "d8",
    baseHP: 8,
    savingThrows: ["dexterity", "charisma"],
    skillChoices: 3,
    availableSkills: allSkills,
    spellcastingAbility: "charisma",
    spellSlots: [{ level: 1, slots: 2 }],
    classConsumables: [
      {
        label: "Bardic Inspiration",
        uses: "{{ modifier abilities.charisma }}",
        resetOn: "long-rest",
      },
    ],
    acTemplate: null,
    optimizedAbilities: { strength: 8, dexterity: 14, constitution: 12, intelligence: 10, wisdom: 13, charisma: 15 },
  },
  Cleric: {
    name: "Cleric",
    hitDice: "d8",
    baseHP: 8,
    savingThrows: ["wisdom", "charisma"],
    skillChoices: 2,
    availableSkills: ["History", "Insight", "Medicine", "Persuasion", "Religion"],
    spellcastingAbility: "wisdom",
    spellSlots: [{ level: 1, slots: 2 }],
    classConsumables: [],
    acTemplate: null,
    optimizedAbilities: { strength: 8, dexterity: 10, constitution: 14, intelligence: 12, wisdom: 15, charisma: 13 },
  },
  Druid: {
    name: "Druid",
    hitDice: "d8",
    baseHP: 8,
    savingThrows: ["intelligence", "wisdom"],
    skillChoices: 2,
    availableSkills: [
      "Arcana",
      "Animal Handling",
      "Insight",
      "Medicine",
      "Nature",
      "Perception",
      "Religion",
      "Survival",
    ],
    spellcastingAbility: "wisdom",
    spellSlots: [{ level: 1, slots: 2 }],
    classConsumables: [],
    acTemplate: null,
    optimizedAbilities: { strength: 8, dexterity: 10, constitution: 14, intelligence: 12, wisdom: 15, charisma: 13 },
  },
  Fighter: {
    name: "Fighter",
    hitDice: "d10",
    baseHP: 10,
    savingThrows: ["strength", "constitution"],
    skillChoices: 2,
    availableSkills: [
      "Acrobatics",
      "Animal Handling",
      "Athletics",
      "History",
      "Insight",
      "Intimidation",
      "Perception",
      "Survival",
    ],
    spellcastingAbility: null,
    spellSlots: [],
    classConsumables: [{ label: "Second Wind", uses: 1, resetOn: ["short-rest", "long-rest"] }],
    acTemplate: null,
    optimizedAbilities: { strength: 15, dexterity: 13, constitution: 14, intelligence: 8, wisdom: 12, charisma: 10 },
  },
  Monk: {
    name: "Monk",
    hitDice: "d8",
    baseHP: 8,
    savingThrows: ["strength", "dexterity"],
    skillChoices: 2,
    availableSkills: ["Acrobatics", "Athletics", "History", "Insight", "Religion", "Stealth"],
    spellcastingAbility: null,
    spellSlots: [],
    classConsumables: [],
    acTemplate: "{{ add 10 (modifier abilities.dexterity) (modifier abilities.wisdom) }}",
    optimizedAbilities: { strength: 8, dexterity: 15, constitution: 13, intelligence: 10, wisdom: 14, charisma: 12 },
  },
  Paladin: {
    name: "Paladin",
    hitDice: "d10",
    baseHP: 10,
    savingThrows: ["wisdom", "charisma"],
    skillChoices: 2,
    availableSkills: ["Athletics", "Insight", "Intimidation", "Medicine", "Persuasion", "Religion"],
    spellcastingAbility: null,
    spellSlots: [],
    classConsumables: [
      {
        label: "Divine Sense",
        uses: "{{ add 1 (modifier abilities.charisma) }}",
        resetOn: "long-rest",
      },
      { label: "Lay on Hands", uses: 5, resetOn: "long-rest" },
    ],
    acTemplate: null,
    optimizedAbilities: { strength: 15, dexterity: 8, constitution: 13, intelligence: 10, wisdom: 12, charisma: 14 },
  },
  Ranger: {
    name: "Ranger",
    hitDice: "d10",
    baseHP: 10,
    savingThrows: ["strength", "dexterity"],
    skillChoices: 3,
    availableSkills: [
      "Animal Handling",
      "Athletics",
      "Insight",
      "Investigation",
      "Nature",
      "Perception",
      "Stealth",
      "Survival",
    ],
    spellcastingAbility: null,
    spellSlots: [],
    classConsumables: [],
    acTemplate: null,
    optimizedAbilities: { strength: 8, dexterity: 15, constitution: 12, intelligence: 10, wisdom: 14, charisma: 13 },
  },
  Rogue: {
    name: "Rogue",
    hitDice: "d8",
    baseHP: 8,
    savingThrows: ["dexterity", "intelligence"],
    skillChoices: 4,
    availableSkills: [
      "Acrobatics",
      "Athletics",
      "Deception",
      "Insight",
      "Intimidation",
      "Investigation",
      "Perception",
      "Performance",
      "Persuasion",
      "Sleight of Hand",
      "Stealth",
    ],
    spellcastingAbility: null,
    spellSlots: [],
    classConsumables: [],
    acTemplate: null,
    optimizedAbilities: { strength: 8, dexterity: 15, constitution: 12, intelligence: 14, wisdom: 13, charisma: 10 },
  },
  Sorcerer: {
    name: "Sorcerer",
    hitDice: "d6",
    baseHP: 6,
    savingThrows: ["constitution", "charisma"],
    skillChoices: 2,
    availableSkills: ["Arcana", "Deception", "Insight", "Intimidation", "Persuasion", "Religion"],
    spellcastingAbility: "charisma",
    spellSlots: [{ level: 1, slots: 2 }],
    classConsumables: [],
    acTemplate: null,
    optimizedAbilities: { strength: 8, dexterity: 12, constitution: 14, intelligence: 10, wisdom: 13, charisma: 15 },
  },
  Warlock: {
    name: "Warlock",
    hitDice: "d8",
    baseHP: 8,
    savingThrows: ["wisdom", "charisma"],
    skillChoices: 2,
    availableSkills: ["Arcana", "Deception", "History", "Intimidation", "Investigation", "Nature", "Religion"],
    spellcastingAbility: "charisma",
    spellSlots: [{ level: 1, slots: 1 }],
    spellSlotResetOn: ["short-rest", "long-rest"],
    classConsumables: [],
    acTemplate: null,
    optimizedAbilities: { strength: 8, dexterity: 12, constitution: 14, intelligence: 10, wisdom: 13, charisma: 15 },
  },
  Wizard: {
    name: "Wizard",
    hitDice: "d6",
    baseHP: 6,
    savingThrows: ["intelligence", "wisdom"],
    skillChoices: 2,
    availableSkills: ["Arcana", "History", "Insight", "Investigation", "Medicine", "Religion"],
    spellcastingAbility: "intelligence",
    spellSlots: [{ level: 1, slots: 2 }],
    classConsumables: [{ label: "Arcane Recovery", uses: 1, resetOn: "long-rest" }],
    acTemplate: null,
    optimizedAbilities: { strength: 8, dexterity: 12, constitution: 14, intelligence: 15, wisdom: 13, charisma: 10 },
  },
  Artificer: {
    name: "Artificer",
    hitDice: "d8",
    baseHP: 8,
    savingThrows: ["constitution", "intelligence"],
    skillChoices: 2,
    availableSkills: ["Arcana", "History", "Investigation", "Medicine", "Nature", "Perception", "Sleight of Hand"],
    spellcastingAbility: "intelligence",
    spellSlots: [{ level: 1, slots: 2 }],
    classConsumables: [],
    acTemplate: null,
    optimizedAbilities: { strength: 8, dexterity: 12, constitution: 14, intelligence: 15, wisdom: 13, charisma: 10 },
  },
};
